/* 
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// InlineResponse2003
    /// </summary>
    [DataContract]
    public partial class InlineResponse2003 :  IEquatable<InlineResponse2003>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2003" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InlineResponse2003() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InlineResponse2003" /> class.
        /// </summary>
        /// <param name="state">-1代表错误 1代表成功 0代表提示 (required).</param>
        /// <param name="msg">状态码对应的详细信息 (required).</param>
        /// <param name="virifycodeid">验证码图片ID (required).</param>
        /// <param name="virifyimage">验证码图片数据data:image/png;base64,格式 (required).</param>
        public InlineResponse2003(string state = default(string), string msg = default(string), string virifycodeid = default(string), string virifyimage = default(string))
        {
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new InvalidDataException("state is a required property for InlineResponse2003 and cannot be null");
            }
            else
            {
                this.State = state;
            }
            
            // to ensure "msg" is required (not null)
            if (msg == null)
            {
                throw new InvalidDataException("msg is a required property for InlineResponse2003 and cannot be null");
            }
            else
            {
                this.Msg = msg;
            }
            
            // to ensure "virifycodeid" is required (not null)
            if (virifycodeid == null)
            {
                throw new InvalidDataException("virifycodeid is a required property for InlineResponse2003 and cannot be null");
            }
            else
            {
                this.Virifycodeid = virifycodeid;
            }
            
            // to ensure "virifyimage" is required (not null)
            if (virifyimage == null)
            {
                throw new InvalidDataException("virifyimage is a required property for InlineResponse2003 and cannot be null");
            }
            else
            {
                this.Virifyimage = virifyimage;
            }
            
        }
        
        /// <summary>
        /// -1代表错误 1代表成功 0代表提示
        /// </summary>
        /// <value>-1代表错误 1代表成功 0代表提示</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// 状态码对应的详细信息
        /// </summary>
        /// <value>状态码对应的详细信息</value>
        [DataMember(Name="msg", EmitDefaultValue=false)]
        public string Msg { get; set; }

        /// <summary>
        /// 验证码图片ID
        /// </summary>
        /// <value>验证码图片ID</value>
        [DataMember(Name="virifycodeid", EmitDefaultValue=false)]
        public string Virifycodeid { get; set; }

        /// <summary>
        /// 验证码图片数据data:image/png;base64,格式
        /// </summary>
        /// <value>验证码图片数据data:image/png;base64,格式</value>
        [DataMember(Name="virifyimage", EmitDefaultValue=false)]
        public string Virifyimage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2003 {\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Msg: ").Append(Msg).Append("\n");
            sb.Append("  Virifycodeid: ").Append(Virifycodeid).Append("\n");
            sb.Append("  Virifyimage: ").Append(Virifyimage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InlineResponse2003);
        }

        /// <summary>
        /// Returns true if InlineResponse2003 instances are equal
        /// </summary>
        /// <param name="input">Instance of InlineResponse2003 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2003 input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                ) && 
                (
                    this.Msg == input.Msg ||
                    (this.Msg != null &&
                    this.Msg.Equals(input.Msg))
                ) && 
                (
                    this.Virifycodeid == input.Virifycodeid ||
                    (this.Virifycodeid != null &&
                    this.Virifycodeid.Equals(input.Virifycodeid))
                ) && 
                (
                    this.Virifyimage == input.Virifyimage ||
                    (this.Virifyimage != null &&
                    this.Virifyimage.Equals(input.Virifyimage))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                if (this.Msg != null)
                    hashCode = hashCode * 59 + this.Msg.GetHashCode();
                if (this.Virifycodeid != null)
                    hashCode = hashCode * 59 + this.Virifycodeid.GetHashCode();
                if (this.Virifyimage != null)
                    hashCode = hashCode * 59 + this.Virifyimage.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
