/* 
 * 扩展接入
 *
 * 接入jugugu区块链全包的全部接口，访问IP需要连续管理员，添加业务服务器IP
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DefaultApi
            //Assert.IsInstanceOf(typeof(DefaultApi), instance);
        }

        
        /// <summary>
        /// Test FriendLoginPost
        /// </summary>
        [Test]
        public void FriendLoginPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InlineObject4 inlineObject4 = null;
            //var response = instance.FriendLoginPost(inlineObject4);
            //Assert.IsInstanceOf(typeof(InlineResponse2002), response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test JuguguGetPhoneCodePost
        /// </summary>
        [Test]
        public void JuguguGetPhoneCodePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InlineObject2 inlineObject2 = null;
            //var response = instance.JuguguGetPhoneCodePost(inlineObject2);
            //Assert.IsInstanceOf(typeof(InlineResponse2002), response, "response is InlineResponse2002");
        }
        
        /// <summary>
        /// Test JugugugGetReleaseNFT1155PNGCodePost
        /// </summary>
        [Test]
        public void JugugugGetReleaseNFT1155PNGCodePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InlineObject3 inlineObject3 = null;
            //var response = instance.JugugugGetReleaseNFT1155PNGCodePost(inlineObject3);
            //Assert.IsInstanceOf(typeof(InlineResponse2003), response, "response is InlineResponse2003");
        }
        
        /// <summary>
        /// Test TransferNFTPost
        /// </summary>
        [Test]
        public void TransferNFTPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InlineObject1 inlineObject1 = null;
            //var response = instance.TransferNFTPost(inlineObject1);
            //Assert.IsInstanceOf(typeof(InlineResponse2001), response, "response is InlineResponse2001");
        }
        
        /// <summary>
        /// Test UserNFTsPost
        /// </summary>
        [Test]
        public void UserNFTsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //InlineObject inlineObject = null;
            //var response = instance.UserNFTsPost(inlineObject);
            //Assert.IsInstanceOf(typeof(InlineResponse200), response, "response is InlineResponse200");
        }
        
    }

}
